worker_processes  auto; #make it 1 - auto to handle more concurrent requests

events {
    worker_connections  1024; #make it more to handle more concurrent requests (worker_processes * worker_connections)
}

http {
    include mime.types; # includes the file type in the request (by deafult it doesn't)

    server {
        listen 80;
        server_name localhost;

        location /api/v1/admin/ {
            client_max_body_size 50M;
            proxy_set_header Connection ""; # Enables Keep-Alive to the backend
            proxy_set_header Host spotify-admin-service-beta.vercel.app; # Remember where the actaul request came from (if not given then shows nginx)
            proxy_set_header X-Real-IP $remote_addr; # Remember where the actaul request came from (if not given then shows nginx)
            proxy_ssl_server_name on;
            proxy_pass https://spotify-admin-service-beta.vercel.app;
        }

        location /api/v1/user/ {
            proxy_set_header Connection ""; # Enables Keep-Alive to the backend
            proxy_set_header Host spotify-user-service-sigma.vercel.app;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_ssl_server_name on;
            proxy_pass https://spotify-user-service-sigma.vercel.app;
        }

        location /api/v1/song/ {
            proxy_set_header Connection ""; # Enables Keep-Alive to the backend
            proxy_set_header Host spotify-song-service-9lmd.onrender.com;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_ssl_server_name on;
            proxy_pass https://spotify-song-service-9lmd.onrender.com;
        }
    }
}